# Generated by Django 5.2.3 on 2025-06-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historyquiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AddField(
            model_name='question',
            name='is_favorites',
            field=models.BooleanField(default=False),
        ),
    ]
