# Generated by Django 5.2.3 on 2025-06-22 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historyquiz', '0003_remove_question_is_favorites_questionfavorites_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=320, unique=True, verbose_name='Слаг (URL)')),
            ],
            options={
                'verbose_name': 'Категория вопроса',
                'verbose_name_plural': 'Категории вопросов',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=160),
        ),
        migrations.AddField(
            model_name='categoryquestions',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='historyquiz.topicquestion'),
        ),
    ]
