# Generated by Django 5.2.3 on 2025-06-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historyquiz', '0004_topicquestion_alter_answer_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicquestion',
            options={'ordering': ['name'], 'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AddField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('answer_options', 'Варианты ответов'), ('typed_answer', 'Напечатанный ответ')], default='answer_options', max_length=32),
        ),
    ]
